version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    command: mongod --quiet --port 1002
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mongo/database:/data/db
      - ./source:/data/log
    ports:
      - "1002:1002"
    restart: unless-stopped
    networks:
      net_internal:
        ipv4_address: 192.168.55.7

networks:
  net_internal:
    external: false
    ipam:
      config:
        - subnet: 192.168.55.0/24
          gateway: 192.168.55.1

  net_external:
    external: true
    name: net_external

